<a href="https://colab.research.google.com/github/ChakaimookZ/241-2567-820/blob/main/5555_Python01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
print("hello"+"world")
print("hello"+""+"world")
print()

helloworld
helloworld

In [18]:
# int
a = 1
a

1

In [19]:
# float

# str (string) เป็นข้อมูล **ข้อความ**

In [20]:
str(a) + "1"

'11'

rqrqrq

In [21]:
print(1+2+3)

6

In [22]:
type(a)

int

In [23]:
b = "python"
b

'python'

error เพราะ

In [24]:
# ทบทวนตัวแปร
print()

# การสรา้ง **list** จาก ตัวแปร []

In [25]:
empty_list = []
print(empty_list)

[]

# การสร้าง list *จากตัวแปรที่สร้างขึ้น*

In [26]:
I = [b,a,2+3,]
I

['python', 1, 5]

In [27]:
len(I)

3

In [28]:
I.pop()
I

['python', 1]

In [29]:
t = (0,1,2,3,4)

In [ ]:
len(t)

5

In [30]:
t [0:3]

(0, 1, 2)

# **การเข้าถึง ข้อมูลตัวสุดท้ายของ tuple**

In [31]:
t[-1]

4

# **การเข้าถึง ข้อมูล ตัวที่สามจากท้ายสุดของ tuple**

In [32]:
t[-3:]

(2, 3, 4)

# **Dictionary เป็น data structure ที่เก็บในลักษณะ key**

In [16]:
grade = {
    "A" : 80,
    "B" : 70,
    "c" : 60,
    "D" : 50,
    "F" : 0
}
grade

{'A': 80, 'B': 70, 'c': 60, 'D': 50, 'F': 0}

In [33]:
grade["A"]

80

In [34]:
grade["B+"] = 75
grade

{'A': 80, 'B': 70, 'c': 60, 'D': 50, 'F': 0, 'B+': 75}

# **การสร้าง dictionary ว่าง และเพิ่มหรืออัปเดตค่า key value**

In [35]:
d = {}
d["s001"] = "Perth"
d["s002"] = "Fon"

In [36]:
d["s001"]

'Perth'

# **String จะคล้ายคลึงกับ List**

In [37]:
sentence = " Hello Python. I am ready. "

In [38]:
sentence[1]

'H'

# **การตัดบางส่วนของ String โดยใชเครื่องหมาย :**

In [39]:
sentence[1:13]

'Hello Python'

# **Strip คือการลบช่องว่าง หัวท้าย**

In [40]:
sentence .strip()

'Hello Python. I am ready.'

In [41]:
list_of_word = sentence.split()

In [42]:
corgi = ''.join(list_of_word)
corgi

'HelloPython.Iamready.'

# **Loop and Condition **

# **For loop**

In [43]:
I

['python', 1]

In [44]:
for item in I:
  print(item)

python
1

In [45]:
for i in range(10):
  print(i)

0
1
2
3
4
5
6
7
8
9

In [46]:
t

(0, 1, 2, 3, 4)

# **List Comprehension**
การวน for loop เพื่อที่จะได้ output

In [47]:
# list Comprehension
list_t = [i for i in t]

# **ดับเบิลคลิก (หรือกด Enter) เพื่อแก้ไข**

In [48]:
[i + 1 for i in range(100)]

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100]

# **if condition**
# **จะทำตามเงื่อนไข ก็ต่อเมื่อเป็นจริงเท่านั้น**

In [49]:
if len(t) ==5:
  print("length is 5")
else:
    print("length not equals 5")

length is 5

# **ตัวอย่าง โค้ดการตัดเกรด จากตัวแปร score**

In [50]:
# ทบทวนตัวแปร grade ตัวเต็ม
grade

{'A': 80, 'B': 70, 'c': 60, 'D': 50, 'F': 0, 'B+': 75}

In [51]:
score = 75
if score >= grade["A"]:
  print("A")
elif score >= grade["B+"]:
  print("B+")
elif score >= grade["B"]:
  print("B")
elif score >= grade["C"]:
  print("C")
elif score >= grade["D"]:
  print("D")
else:
  print("F")

B+

In [52]:
def circle_area(r):
  return pi * r * r

  circle_area(2)

In [53]:
def conversion(amount, rate=31.33):
  return amount * rate

  conversion(30)

In [54]:
conversion(30, 33.3333)

999.999

In [55]:
file = open("output.csv", "w")
file.write("Hello World")
file.close()

In [9]:
header = ["date", "item", "price"]
",".join(header) + "\n"

'date,item,price\n'

In [10]:
header = ["date", "item", "price"]
content = [
    ("2020-02-07","Milk","26.5"),
    ("2020-02-08","Water","7"),
    ("2020-02-08","Mask","20"),
    ("2020-02-08","Lays","10"),
    ("2020-02-08","Rice","6"),
]

file = open('product.csv', 'w')
file.write(",".join(header) + "\n")

for item in content:
  file.write(",".join(item) + "\n")

file.close()

In [11]:
import pandas as pd

df = pd.read_csv('sample_data/california_housing_test.csv')
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0
...,...,...,...,...,...,...,...,...,...
2995,-119.86,34.42,23.0,1450.0,642.0,1258.0,607.0,1.1790,225000.0
2996,-118.14,34.06,27.0,5257.0,1082.0,3496.0,1036.0,3.3906,237200.0
2997,-119.70,36.30,10.0,956.0,201.0,693.0,220.0,2.2895,62000.0
2998,-117.12,34.10,40.0,96.0,14.0,46.0,14.0,3.2708,162500.0
2999,-119.63,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608,500001.0

In [12]:
type(df)

pandas.core.frame.DataFrame

In [13]:
df.to_csv('new_data.csv')

In [56]:
grade

{'A': 80, 'B': 70, 'c': 60, 'D': 50, 'F': 0, 'B+': 75}

In [57]:
import json
json.dumps(grade)

'{"A": 80, "B": 70, "c": 60, "D": 50, "F": 0, "B+": 75}'

In [58]:
type(json.dumps(grade))

str

In [59]:
# Save to output file grade.json
json.dump(grade, open('grade.json', 'w'))

In [ ]:
students = json.loads('{"stusent1": "Perth", "student2": "Fon"}')
students

{'stusent1': 'Perth', 'student2': 'Fon'}

In [90]:
type(students)

NameError: name 'students' is not defined

In [62]:
bool("")

False

In [3]:
import ast
ast.literal_eval('False')

False

In [ ]:
import this

In [7]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [64]:
#อ่านข้อมูลจากไฟล์ study.csv
df = pd.read_csv('study.csv')
df.head()

   Hours  Scores
0    2.5      21
1    5.1      47
2    3.2      27
3    8.5      75
4    3.5      30

from matplotlib import pyplot as plt
_df_0['index'].plot(kind='hist', bins=20, title='index')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_1['Hours'].plot(kind='hist', bins=20, title='Hours')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_2['Scores'].plot(kind='hist', bins=20, title='Scores')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_3.plot(kind='scatter', x='index', y='Hours', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_4.plot(kind='scatter', x='Hours', y='Scores', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['index']
  ys = series['Hours']

  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_5.sort_values('index', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('index')
_ = plt.ylabel('Hours')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['index']
  ys = series['Scores']

  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_6.sort_values('index', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('index')
_ = plt.ylabel('Scores')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series['index']
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': 'index'}, axis=1)
              .sort_values('index', ascending=True))
  xs = counted['index']
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_7.sort_values('index', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('index')
_ = plt.ylabel('count()')

from matplotlib import pyplot as plt
_df_8['index'].plot(kind='line', figsize=(8, 4), title='index')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_9['Hours'].plot(kind='line', figsize=(8, 4), title='Hours')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_10['Scores'].plot(kind='line', figsize=(8, 4), title='Scores')
plt.gca().spines[['top', 'right']].set_visible(False)

In [65]:
#ตรวจสอบว่ามีคอลัมอะไรบ้าง
df.columns

Index(['Hours', 'Scores'], dtype='object')

In [66]:
input_columns = ['Hours'] #แก้
output_columns = ['Scores'] #แก้

In [72]:
X = df[input_columns]
y = df[output_columns]

In [68]:
#X.shape

In [73]:
# splitting the data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.20, random_state=1,)

In [74]:
# Linear Regression
from sklearn.linear_model import LinearRegression
model = LinearRegression() #สร้าง model : y=mx + b
model.fit(X_train, y_train) # เรียน หาค่า m กับ b ออกมา

LinearRegression()

In [76]:
# แสดงค่า m และ b
print(model.intercept_) # b จุดตัดแกน y
print(model.coef_) # m ความชัน

[1.18964733]
[[10.12113087]]

In [78]:
#ทำนายบนชุดทดสอบ
y_p = model.predict(X_test)

In [79]:
#วัดผล MSE
from sklearn import metrics
print(np.sqrt(metrics.mean_squared_error(y_test, y_p)))

6.718379948116893

In [80]:
#หากเรียน 7.5,8.5,9.25
X_quiz = [[7.5], [8.5], [9.25]]
y_quiz = model.predict(X_quiz)
print(y_quiz)

[[77.09812883]
 [87.21925969]
 [94.81010784]]

In [83]:
#ใช้ model  ที่ได้ หากเรียน 12.2,15.3,1,0,6,7.2
#จะได้คะแนนเท่าใด
X_quiz = [[12.2], [15.3], [1], [0], [6], [7.2]]
y_quiz = model.predict(X_quiz)
print(y_quiz)

[[124.66744389]
 [156.04294958]
 [ 11.3107782 ]
 [  1.18964733]
 [ 61.91643253]
 [ 74.06178957]]

In [84]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [85]:
#อ่านข้อมูลจากไฟล์ study.csv
df = pd.read_csv('insurance.csv')
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [86]:
#ตรวจสอบว่ามีคอลัมอะไรบ้าง
df.columns

Index(['age', 'sex', 'bmi', 'children', 'smoker', 'region', 'charges'], dtype='object')

In [87]:
#กำจัดค่าว่าง
df.dropna(inplace = True )

In [88]:
input_columns = ['age', 'bmi', 'children'] #แก้
output_columns = ['charges'] #แก้

In [89]:
X = df.loc[:, input_columns]
y = df.loc[:, output_columns]

In [91]:
# splitting the data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.20, random_state=1,)

In [92]:
# Linear Regression
from sklearn.linear_model import LinearRegression
model = LinearRegression() #สร้าง model : y=mx + b
model.fit(X_train, y_train) # เรียน หาค่า m กับ b ออกมา

LinearRegression()

In [93]:
# แสดงค่า m และ b
print(model.intercept_) # b จุดตัดแกน y
print(model.coef_) # m ความชัน

[-5889.3730808]
[[246.43462275 300.89595729 254.64158627]]

In [94]:
#ทำนายบนชุดทดสอบ
y_p = model.predict(X_test)

In [95]:
#วัดผล MSE
from sklearn import metrics
print(np.sqrt(metrics.mean_squared_error(y_test, y_p)))

11380.3421565389

In [98]:
#ใช้ model ที่ได้ ทำนายเบี้ยประกัน #แก้
#age = 30, bmi=35, childen = 1
#age = 19, bmi=25, childen = 2
#age = 41, bmi=23, childen = 0
X_quiz = [[30, 35, 1], [19, 25, 2], [41, 23, 0]]
y_quiz = model.predict(X_quiz)
print(y_quiz)

[[12289.66569339]
 [ 6824.56685643]
 [11135.05346989]]